services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - microservices

      
  postgresql:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_DB_PASSWORD}
      - POSTGRES_DB=${PRODUCT_DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    networks:
      - microservices


volumes:
  mongo:
  postgres:

networks:
  microservices:
    driver: bridge